### ISSUE TITLE
[Request feature] shareable links

### ISSUE THREAD

**Issue by X7md** [matschik/component-party.dev#161]
E.g: 
```
https://component-party.dev?select=vue,react
```
![IMG_7452](https://user-images.githubusercontent.com/54203033/229063641-6a075b0a-8526-4f41-ab8c-296adf2fb862.jpeg)

**Comment by X7md** [comment]
I guess it's already implement, but not clear hoe to use it...
https://github.com/matschik/component-party/blob/11975c888a99a4499d695365a92d1345d5edf55b/src/App.svelte#L36

**Comment by mroeling** [comment]
It is! E.g. https://component-party.dev/?f=aurelia1,react

**Comment by X7md** [comment]
> It is! E.g. https://component-party.dev/?f=aurelia1,react
> 
> Or in your case: https://component-party.dev/?f=react,vue3

Will be nice if url change and add parameter automatically on button change.

**Comment by matschik** [comment]
solved by https://github.com/matschik/component-party.dev/commit/08c89c88efcf2999b5bc0e2ba79195b1c8a65433
