### ISSUE TITLE
Svelte actions would obsolete dom ref example

### ISSUE THREAD

**Issue by brunnerh** [matschik/component-party.dev#173]
One can get a reference with `bind:this`, but it is often not necessary because there are [actions](https://svelte.dev/docs/element-directives#use-action).

The "dom ref" example:

```svelte
<script>
  import { onMount } from "svelte";

  let inputElement;

  onMount(() => {
    inputElement.focus();
  });
</script>

<input bind:this={inputElement} />
```

Could be replaced with just:
```svelte
<script>
  const focus = node => node.focus();
</script>

<input use:focus />
```

Actions probably do not have an equivalent in most libraries, but the current example is just so unnecessarily clunky...

**Comment by matschik** [comment]
The goal in the snippet named "Dom ref" is not to show how to focus an input.
The goal here is to show how to make a dom ref compared to other frameworks.

Component Party is focused on clarity when comparing with other frameworks, not over-optimization.

**Comment by brunnerh** [comment]
I am aware of all that, the problem I have with the current code is that it gives a false impression/is not representative of code one *should* write. I also did not have clear way of fixing that, which is why I opened the issue.

**Comment by matschik** [comment]
It just shows how to do a dom ref. So the problem is solved.
We don't need to go further. When you are learning Svelte from React or Vue for example, your proposition would be very confusing to make a dom ref event if it's interesting.
