### ISSUE TITLE
React computed state example should use `useMemo` hook

### ISSUE THREAD

**Issue by Lsnsh** [matschik/component-party.dev#181]
> ![image](https://github.com/matschik/component-party.dev/assets/26019513/281e9cb2-55ef-4d7f-9472-01578237f5f0)

https://react.dev/reference/react/useMemo

> ![image](https://github.com/matschik/component-party.dev/assets/26019513/07aec910-6ef3-42d9-99a1-b48316364c53)

https://vuejs.org/guide/essentials/computed.html#computed-caching-vs-methods

![image](https://github.com/matschik/component-party.dev/assets/26019513/a7b00727-dee7-4718-9e73-3406f71a6f48)

In actual coding, if only have some easy calculate, use expression is better, because hook also have expenses

- https://react.dev/reference/react/useMemo#how-to-tell-if-a-calculation-is-expensive
- https://react.dev/reference/react/useMemo#should-you-add-usememo-everywhere

**Comment by matschik** [comment]
Duplicate https://github.com/matschik/component-party.dev/issues/61

**Comment by matschik** [comment]
Other examples don't use memoization. If you want `useMemo` to be featured, please check out this issue: https://github.com/matschik/component-party.dev/issues/122
