### ISSUE TITLE
Add line numbers

### ISSUE THREAD

**Issue by Snailedlt** [matschik/component-party.dev#189]
## What?
Line numbers inside the code blocks

## Why? 
There's a significant correlation between the number of lines of code and the number of bugs in software. Therefore it would be very useful if we could see the line numbers in the code blocks, to see which frameworks are the least verbose, and therefore easiest to prevent future bugs.

**Comment by Snailedlt** [comment]
Would also be nice if we could see the total line number for all files in a way

**Comment by matschik** [comment]
If we do that, there will be a war with format/linting config to have their favorite framework having the less nb of lines as possible. For example, people will abuse using ternary syntax to optimize nb of lines. Component Party will be harder to maintain for no reason.
Actually a simple and understandable code is more important than the numbers of line. Number of lines is actually not that important.
Please, let's focus on more important things like: having understandable examples, good variable names, etc...
