### ISSUE TITLE
Shareable URLs for Components Comparisons

### ISSUE THREAD

**Issue by push-on** [matschik/component-party.dev#191]
When comparing multiple components on the website, it would be very useful if the URL could reflect the selections made. For example, if I'm comparing Component A and Component B, the URL could contain something like website.com/users+ComponentA+ComponentB. This would make it easy to share a link with someone that includes the specific components I have selected for comparison. By updating the URL parameters as selections change, the link could always show the current comparison. Please consider adding this functionality so comparisons are easier to share.

**Comment by matschik** [comment]
Already available but kinda hidden. Let's find a good way to show that !
Example: `https://component-party.dev/?f=vue3,react`

**Comment by matschik** [comment]
The only thing to consider is the conflict with user localstorage frameworks selection is we update the url realtime.

**Comment by anton-gustafsson** [comment]
This would be a great feature! 🚀

**Comment by matschik** [comment]
solved by https://github.com/matschik/component-party.dev/commit/08c89c88efcf2999b5bc0e2ba79195b1c8a65433
