### ISSUE TITLE
Improve the framework navbar

### ISSUE THREAD

**Issue by khang-nd** [matschik/component-party.dev#192]
Hello @matschik, first of all, this project idea is brilliant, I've always wanted to see something like this as the front-end frameworks just keep evolving at a rapid pace. Kudos! 👍

Just wanted to add feedback regarding the framework navigation. Not sure if many people are experiencing this but as I have a habit of having my browser zoomed in a bit for better viewability, and the navigation does not show all the available frameworks (even the "more" button is hidden), so at first glance, I totally assumed quite a few frameworks missing until I zoomed it out.

Would be good if we could do something to improve the viewability of the framework navigation.

![](https://github.com/matschik/component-party.dev/assets/55619201/38cd3c2e-b1d6-438e-a95a-66b2facf2ef5)

**Comment by gustavomorinaga** [comment]
@khang-nd, I opened a PR that fixes this bug: #207

**Comment by khang-nd** [comment]
Issue resolved thanks to @gustavomorinaga
