### ISSUE TITLE
Add Knockout.JS

### ISSUE THREAD

**Issue by KiddoV** [matschik/component-party.dev#212]
I know [KnockoutJS](https://knockoutjs.com/) is old and no longer maintain, but it would be nice to include.
This will help the migration of KnockoutJS to a newer framework.

Thanks,

**Comment by matschik** [comment]
If you want to add KnockoutJS, feel free to make a PR and follow [Add a framework](https://github.com/matschik/component-party.dev?tab=readme-ov-file#add-a-new-framework) guide.

Be aware, you will have a responsability to maintain the quality of this framework's snippets.
I close it for now, you can reopen it once you are making the PR.
