### ISSUE TITLE
Control Flow Changes in Angular Is Not a Stable Feature

### ISSUE THREAD

**Issue by dinnerhe** [matschik/component-party.dev#216]
I see that #213 #214 updates the examples to Angular 17's built-in control flow feature. While personally I really like the new syntax, as [Angular documentation](https://angular.io/guide/control_flow) states, it is "in [Developer Preview](https://angular.io/guide/releases#developer-preview)" and "may change before becoming stable". Although the developer preview features usually become stable in the next main version of Angular, it is subject to change for now.

**Comment by matschik** [comment]
Thanks for your explanation, I reverted #213 and #214 since Component Party must only show the stable syntax of frameworks.
