### ISSUE TITLE
The code of Vue2 framework in the lifecycle is incorrect

### ISSUE THREAD

**Issue by EthanLiu2022** [matschik/component-party.dev#243]
![image](https://github.com/user-attachments/assets/a93a9645-c2f6-4ce1-97ca-700551073fd4)

`beforeUnmount() {
    clearInterval(this.timer);
  },`
Change to
`beforeDestory() {
    clearInterval(this.timer);
  },`

**Comment by matschik** [comment]
Can you give me a link to the documentation about that ?
`beforeUnmount` seems valid: https://vuejs.org/api/options-lifecycle.html#beforeunmount

**Comment by EthanLiu2022** [comment]
this is the link: [https://v2.vuejs.org/v2/api/#beforeDestroy](url)
The link you gave is the documentation of vue3。

**Comment by matschik** [comment]
So they introduced a breaking change on Options API in Vue 3. That's strange...
Always provide a documentation link to support your proposition.

**Comment by EthanLiu2022** [comment]
To be precise, Vue3 supports the APIs of Vue2, but Vue2 does not support some APIs in Vue3, such as beforeUnmount you wrote.
So in your document, using beforeUnmount in Vue2 will report an error.
You can actually run the code you wrote and see the effect.
