### ISSUE TITLE
Inaccurate Svelte 5 example 

### ISSUE THREAD

**Issue by cowboycodr** [matschik/component-party.dev#272]
content/1-reactivity/1-declare-state/svelte5/Name.svelte

Currently:
```svelte
<script>
  let name = $state("John");
</script>

<h1>Hello {name}</h1>
```
However since `name` isn't reactive in this example it would actually be
```svelte
<script>
  let name = "John";
</script>

<h1>Hello {name}</h1>
```

**Comment by matschik** [comment]
Sure but the name of the snippet is "Declare state". This is exactly what we are doing. 
Same thing for the other frameworks examples.
