### ISSUE TITLE
Request to indent Vue scripts and styles

### ISSUE THREAD

**Issue by sheriffderek** [matschik/component-party.dev#284]
I know that Evan doesn't do this... 

https://component-party.dev/compare/vue3-vs-svelte5

But I think it would be easier to read. And comparing to Svelte in situations where they are essentially the same, the Vue looks more dense and hard to read because of the indent alone.

![CleanShot 2024-12-03 at 11 33 34@2x](https://github.com/user-attachments/assets/ee99cbf5-01cc-499a-8e85-d2277726297c)

**Comment by matschik** [comment]
We are using the official eslint/prettier vue config formatting. If we start making custom config based on some user preferences, this project will be very hard to maintain. So we stick to the official plugins defaults.
