### ISSUE TITLE
React: find or create a React REPL

### ISSUE THREAD

**Issue by matschik** [matschik/component-party.dev#44]
It must:
- support multiple files
- hash code source encoding like Svelte REPL or Vue3 REPL

Vue3 example: https://sfc.vuejs.org/#eyJOYW1lLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnO1xuY29uc3QgbmFtZSA9IHJlZignSm9obicpO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblx0PGgxPkhlbGxvIHt7IG5hbWUgfX08L2gxPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcInZ1ZVwiOlwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJ9In0=

Svelte example:
https://svelte-repl.vercel.app/#W3sibmFtZSI6Ik5hbWUiLCJ0eXBlIjoic3ZlbHRlIiwic291cmNlIjoiPHNjcmlwdD5cblx0bGV0IG5hbWUgPSAnSm9obic7XG48L3NjcmlwdD5cblxuPGgxPkhlbGxvIHtuYW1lfTwvaDE+XG4ifV0=

Attempt with Preact REPL: #25

**Comment by ndom91** [comment]
While the Preact REPL did work well with most of the basic React-based examples, it unfortunately did not have support for multi-file examples. Therefore rendering it (hehe) useless for many of the examples here :/
